import type { Metadata } from "next";
import "./globals.css";
import Header from "@/_components/Header";
import { getCurrentUser } from "@/_lib/getUsersApi";

export const metadata: Metadata = {
  title: {
    template: "%s / Todo App",
    default: "Welcome Todo App",
  },
  description: "Generated by Next.js and Ruby on Rails",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let me = null;
  try {
    me = await getCurrentUser();
  } catch {}

  return (
    <html lang="ja" className={`h-full antialiased`}>
      <body className="min-h-screen flex flex-col bg-[#DDE6ED]">
        <Header name={me?.name} />
        <main className="mx-auto w-full max-w-xl flex-1">{children}</main>
      </body>
    </html>
  );
}
