import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/_components/Header";
import { getCurrentUser } from "@/_lib/getUsersApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s / Todo App",
    default: "Welcome Todo App",
  },
  description: "Generated by Next.js and Ruby on Rails",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let me = null;
  try {
    me = await getCurrentUser();
  } catch {}

  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#DDE6ED]">
        <Header name={me?.name} />
        <main className="mx-auto w-full max-w-xl flex-1">{children}</main>
      </body>
    </html>
  );
}
